// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

import {IRiscZeroVerifier} from "risc0/IRiscZeroVerifier.sol";
import {Steel} from "../steel/Steel.sol";

/// @title CrossingCounterZKSteel
/// @notice Verifies crossing-count proofs generated by a RISC Zero Steel guest.
///         The guest runs the CrossingCount Solidity bytecode inside the
///         zkVM via Steel's EVM interpreter, then commits a Steel block
///         commitment followed by (crossing_count, input_hash,
///         contract_address) in risc0-serde format.
/// @dev Journal layout (312 bytes total):
///        bytes   0..95:  Steel Commitment (3 x uint256, ABI-encoded)
///        bytes  96..103: crossing_count as u64 LE (2 u32 words)
///        bytes 104..231: input_hash as 32 u32 LE words
///        bytes 232..311: contract address as 20 u32 LE words
contract CrossingCounterZKSteel {
    IRiscZeroVerifier public immutable VERIFIER;
    bytes32 public immutable IMAGE_ID;
    /// @notice The CrossingCounter deployment the guest must have executed.
    address public immutable CROSSING_COUNTER;

    uint256 public bestCrossings;
    address public bestSolver;
    bytes32 public bestInputHash;

    constructor(IRiscZeroVerifier _verifier, bytes32 _imageId, address _crossingCounter) {
        VERIFIER = _verifier;
        IMAGE_ID = _imageId;
        CROSSING_COUNTER = _crossingCounter;
        bestCrossings = type(uint256).max;
    }

    /// @notice Submit a ZK proof of a Steel crossing-count computation.
    /// @param seal    The Groth16 proof (SNARK).
    /// @param journal The 312-byte journal committed by the Steel guest.
    /// @return crossingCount The crossing count extracted from the journal.
    function verify(bytes calldata seal, bytes calldata journal) external returns (uint256 crossingCount) {
        VERIFIER.verify(seal, IMAGE_ID, sha256(journal));

        require(journal.length == 312, "invalid journal length");

        // Validate the Steel commitment: the guest's EVM execution must have
        // run against a block of this chain (and this chain's config).
        Steel.Commitment memory commitment = abi.decode(journal[0:96], (Steel.Commitment));
        require(Steel.validateCommitment(commitment), "invalid steel commitment");

        // Decode the risc0-serde payload after the Steel commitment.
        crossingCount = _readU64le(journal, 96);
        bytes32 inputHash = _readHashFromWords(journal, 104);
        address journalContract = _readAddressFromWords(journal, 232);

        // The guest commits the address of the contract it executed; without
        // this check the prover could run any contract with a matching
        // selector instead of the canonical CrossingCounter.
        require(journalContract == CROSSING_COUNTER, "contract address mismatch");

        if (crossingCount < bestCrossings) {
            bestCrossings = crossingCount;
            bestSolver = msg.sender;
            bestInputHash = inputHash;
        }
    }

    /// @dev Read a little-endian uint64 from calldata bytes at the given offset.
    function _readU64le(bytes calldata data, uint256 offset) internal pure returns (uint64 v) {
        v = uint64(uint8(data[offset])) | (uint64(uint8(data[offset + 1])) << 8)
            | (uint64(uint8(data[offset + 2])) << 16) | (uint64(uint8(data[offset + 3])) << 24)
            | (uint64(uint8(data[offset + 4])) << 32) | (uint64(uint8(data[offset + 5])) << 40)
            | (uint64(uint8(data[offset + 6])) << 48) | (uint64(uint8(data[offset + 7])) << 56);
    }

    /// @dev Read a bytes32 from 32 consecutive risc0-serde u32 LE words.
    ///      Each word occupies 4 bytes; the hash byte is in the low position.
    function _readHashFromWords(bytes calldata data, uint256 offset) internal pure returns (bytes32 h) {
        for (uint256 i = 0; i < 32; i++) {
            h |= bytes32(uint256(uint8(data[offset + i * 4])) << (248 - 8 * i));
        }
    }

    /// @dev Read an address from 20 consecutive risc0-serde u32 LE words.
    ///      Each word occupies 4 bytes; the address byte is in the low position.
    function _readAddressFromWords(bytes calldata data, uint256 offset) internal pure returns (address a) {
        uint160 v;
        for (uint256 i = 0; i < 20; i++) {
            v |= uint160(uint8(data[offset + i * 4])) << (152 - 8 * i);
        }
        a = address(v);
    }
}
