// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

import {IRiscZeroVerifier} from "risc0/IRiscZeroVerifier.sol";

/// @title CrossingCounterZK
/// @notice Verifies crossing-count proofs generated by a RISC Zero guest
///         program.  The guest computes the crossing count off-chain and
///         commits (crossing_count, input_hash) to the journal.  This
///         contract verifies the Groth16 proof on-chain and tracks the best
///         (lowest) crossing count.
/// @dev The journal is encoded by risc0-serde: 8 bytes u64 LE crossing_count
///      followed by 32 × 4-byte u32 LE words for input_hash (each word holds
///      one byte in its low position).  Total 136 bytes.
contract CrossingCounterZK {
    IRiscZeroVerifier public immutable VERIFIER;
    bytes32 public immutable IMAGE_ID;

    uint256 public bestCrossings;
    address public bestSolver;
    bytes32 public bestInputHash;

    constructor(IRiscZeroVerifier _verifier, bytes32 _imageId) {
        VERIFIER = _verifier;
        IMAGE_ID = _imageId;
        bestCrossings = type(uint256).max;
    }

    /// @notice Submit a ZK proof of a crossing-count computation.
    /// @param seal  The Groth16 proof (SNARK).
    /// @param journal  The 136-byte journal committed by the guest program.
    /// @return crossingCount The crossing count extracted from the journal.
    function verify(bytes calldata seal, bytes calldata journal) external returns (uint256 crossingCount) {
        // Verify the ZK proof against the expected guest image.
        VERIFIER.verify(seal, IMAGE_ID, sha256(journal));

        // Decode journal (risc0-serde encoding):
        //   bytes  0..7:   crossing_count as u64 LE (2 u32 words)
        //   bytes  8..135: input_hash as 32 u32 LE words (low byte of each)
        require(journal.length == 136, "invalid journal length");
        crossingCount = _readU64le(journal, 0);
        bytes32 inputHash = _readHashFromWords(journal, 8);

        if (crossingCount < bestCrossings) {
            bestCrossings = crossingCount;
            bestSolver = msg.sender;
            bestInputHash = inputHash;
        }
    }

    /// @dev Read a little-endian uint64 from calldata bytes at the given offset.
    function _readU64le(bytes calldata data, uint256 offset) internal pure returns (uint64 v) {
        v = uint64(uint8(data[offset])) | (uint64(uint8(data[offset + 1])) << 8)
            | (uint64(uint8(data[offset + 2])) << 16) | (uint64(uint8(data[offset + 3])) << 24)
            | (uint64(uint8(data[offset + 4])) << 32) | (uint64(uint8(data[offset + 5])) << 40)
            | (uint64(uint8(data[offset + 6])) << 48) | (uint64(uint8(data[offset + 7])) << 56);
    }

    /// @dev Read a bytes32 from 32 consecutive risc0-serde u32 LE words.
    ///      Each word occupies 4 bytes; the hash byte is in the low position.
    function _readHashFromWords(bytes calldata data, uint256 offset) internal pure returns (bytes32 h) {
        for (uint256 i = 0; i < 32; i++) {
            h |= bytes32(uint256(uint8(data[offset + i * 4])) << (248 - 8 * i));
        }
    }
}
