// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {console} from "forge-std/console.sol";
import {ControlID, RiscZeroGroth16Verifier} from "risc0/groth16/RiscZeroGroth16Verifier.sol";
import {CrossingCounterZK} from "./CrossingCounterZK.sol";

/// @notice Gas benchmark for ZK crossing-count verification using real
///         Groth16 proofs.  Loads seal and journal from files generated by
///         `cargo run --release -- --groth16` in prover/src/crossing-counter-zk.
///         Each fixture is measured from a clean snapshot so that every
///         measurement includes cold precompile access costs.
contract GasBenchmarkZkTest is Test {
    string constant PROOFS_DIR = "../prover/src/crossing-counter-zk/proofs/";

    function _fixturesDir() internal pure returns (string memory) {
        return "benchmark-fixtures/";
    }

    RiscZeroGroth16Verifier private groth16Verifier;
    CrossingCounterZK private target;

    function setUp() public {
        try vm.readFile(string.concat(PROOFS_DIR, "image_id.txt")) returns (string memory idHex) {
            bytes32 imageId = vm.parseBytes32(idHex);
            groth16Verifier = new RiscZeroGroth16Verifier(ControlID.CONTROL_ROOT, ControlID.BN254_CONTROL_ID);
            target = new CrossingCounterZK(groth16Verifier, imageId);
        } catch {
            vm.skip(true);
        }
    }

    function test_benchmark() public {
        string memory dir = _fixturesDir();
        string memory manifestJson;
        try vm.readFile(string.concat(dir, "manifest.json")) returns (string memory j) {
            manifestJson = j;
        } catch {
            vm.skip(true);
            return;
        }
        string[] memory slugs = abi.decode(vm.parseJson(manifestJson), (string[]));

        for (uint256 i = 0; i < slugs.length; i++) {
            string memory slug = slugs[i];
            string memory fixtureJson = vm.readFile(string.concat(dir, slug, ".json"));
            uint256 expectedCrossings = abi.decode(vm.parseJson(fixtureJson, ".expected_crossings"), (uint256));

            bytes memory rawSeal = vm.readFileBinary(string.concat(PROOFS_DIR, slug, "_seal.bin"));
            bytes memory journal = vm.readFileBinary(string.concat(PROOFS_DIR, slug, "_journal.bin"));
            bytes memory seal = abi.encodePacked(groth16Verifier.SELECTOR(), rawSeal);

            // Snapshot and revert around each verification so that every
            // measurement starts with cold precompile addresses.
            uint256 snapId = vm.snapshot();

            uint256 gasBefore = gasleft();
            uint256 crossings = target.verify(seal, journal);
            uint256 gasUsed = gasBefore - gasleft();

            assertEq(crossings, expectedCrossings);

            vm.revertTo(snapId);

            console.log("  %s: %d gas", slug, gasUsed);
            emit log_named_uint(string.concat(slug, "_gas"), gasUsed);
        }
    }
}
