// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {console} from "forge-std/console.sol";
import {ControlID, RiscZeroGroth16Verifier} from "risc0/groth16/RiscZeroGroth16Verifier.sol";
import {ChainSpec, Encoding, Steel} from "../steel/Steel.sol";
import {CrossingCounterZKSteel} from "./CrossingCounterZKSteel.sol";

/// @notice Gas benchmark for Steel crossing-count verification using real
///         Groth16 proofs.  Loads seal and journal from files generated by
///         `cargo run --release -- --groth16` in prover/src/crossing-counter-zk-steel.
///         Each fixture is measured from a clean snapshot so that every
///         measurement includes cold precompile access costs.
contract GasBenchmarkZkSteelTest is Test {
    string constant PROOFS_DIR = "../prover/src/crossing-counter-zk-steel/proofs/";

    function _fixturesDir() internal pure returns (string memory) {
        return "benchmark-fixtures/";
    }

    RiscZeroGroth16Verifier private groth16Verifier;
    bytes32 private imageId;

    function setUp() public {
        try vm.readFile(string.concat(PROOFS_DIR, "image_id.txt")) returns (string memory idHex) {
            imageId = vm.parseBytes32(idHex);
            groth16Verifier = new RiscZeroGroth16Verifier(ControlID.CONTROL_ROOT, ControlID.BN254_CONTROL_ID);
        } catch {
            vm.skip(true);
        }
    }

    /// @dev Read the CrossingCounter address the guest committed at journal
    ///      offset 232 (20 u32 LE words, address byte in the low position).
    function _journalContractAddress(bytes memory journal) internal pure returns (address a) {
        uint160 v;
        for (uint256 i = 0; i < 20; i++) {
            v |= uint160(uint8(journal[232 + i * 4])) << (152 - 8 * i);
        }
        a = address(v);
    }

    /// @dev Prepare the local chain so that the Steel commitment embedded in
    ///      a real proof journal validates: adopt the proof's chain config
    ///      and recorded block hash.
    function _adoptJournalEnvironment(bytes memory journal) internal {
        bytes memory head = new bytes(96);
        for (uint256 i = 0; i < 96; i++) {
            head[i] = journal[i];
        }
        Steel.Commitment memory commitment = abi.decode(head, (Steel.Commitment));

        uint256[3] memory chainIds = [uint256(1), 11155111, 17000];
        uint256 chainId = 0;
        for (uint256 i = 0; i < chainIds.length; i++) {
            if (commitment.configID == ChainSpec.configID(chainIds[i])) {
                chainId = chainIds[i];
                break;
            }
        }
        require(chainId != 0, "unknown steel config ID in journal");
        vm.chainId(chainId);

        (uint240 blockNumber, uint16 version) = Encoding.decodeVersionedID(commitment.id);
        require(version == 0, "only block commitments supported in benchmark");
        vm.roll(uint256(blockNumber) + 1);
        vm.setBlockhash(blockNumber, commitment.digest);
    }

    function test_benchmark() public {
        string memory dir = _fixturesDir();
        string memory manifestJson;
        try vm.readFile(string.concat(dir, "manifest.json")) returns (string memory j) {
            manifestJson = j;
        } catch {
            vm.skip(true);
            return;
        }
        string[] memory slugs = abi.decode(vm.parseJson(manifestJson), (string[]));

        for (uint256 i = 0; i < slugs.length; i++) {
            string memory slug = slugs[i];
            string memory fixtureJson = vm.readFile(string.concat(dir, slug, ".json"));
            uint256 expectedCrossings = abi.decode(vm.parseJson(fixtureJson, ".expected_crossings"), (uint256));

            bytes memory rawSeal = vm.readFileBinary(string.concat(PROOFS_DIR, slug, "_seal.bin"));
            bytes memory journal = vm.readFileBinary(string.concat(PROOFS_DIR, slug, "_journal.bin"));
            bytes memory seal = abi.encodePacked(groth16Verifier.SELECTOR(), rawSeal);

            uint256 snapId = vm.snapshot();

            _adoptJournalEnvironment(journal);

            // Pin the target to the CrossingCounter deployment the proof was
            // generated against, taken from the proof's own journal.
            CrossingCounterZKSteel target =
                new CrossingCounterZKSteel(groth16Verifier, imageId, _journalContractAddress(journal));

            uint256 gasBefore = gasleft();
            uint256 crossings = target.verify(seal, journal);
            uint256 gasUsed = gasBefore - gasleft();

            assertEq(crossings, expectedCrossings);

            vm.revertTo(snapId);

            console.log("  %s: %d gas", slug, gasUsed);
            emit log_named_uint(string.concat(slug, "_gas"), gasUsed);
        }
    }
}
